const translations = {
    es: {
        entradas: "ENTRADAS",
        platos: "PLATOS",
        postres: "POSTRES",
        bebidas: "BEBIDAS",
        contacto: "CONTACTO",
        welcomeTitle: "Bienvenidos a Mar de Luna",
        welcomeMessage: "En Mar de Luna, nos enorgullece ofrecer una experiencia culinaria única, donde cada plato refleja nuestro compromiso con la excelencia y el sabor auténtico del mar. Con una trayectoria arraigada en la pasión por la cocina y el respeto por los ingredientes frescos y de calidad, hemos construido un legado que nos distingue en el mundo gastronómico.",
        valuesTitle: "Nuestros Valores:",
        quality: "Calidad: Nos esforzamos por ofrecer mariscos frescos y seleccionados con el más alto estándar de calidad en cada uno de nuestros platos.",
        professionalism: "Profesionalismo: Nuestro equipo está compuesto por expertos en el arte culinario, comprometidos con la perfección en cada detalle y con la satisfacción de nuestros comensales.",
        tradition: "Tradición: Con décadas de experiencia en la preparación de delicias marinas, honramos la tradición culinaria y celebramos la riqueza de sabores que el mar nos ofrece.",
        experience: "¡Bienvenidos a una experiencia gastronómica inolvidable en Mar de Luna!",
        chefMessage: "¡Hola! Soy Francis Gollum, el chef ejecutivo en Mar de Luna. Mi pasión es crear experiencias culinarias que celebren los sabores del mar. ¡Únete a mí en un viaje gastronómico donde cada plato cuenta una historia de frescura y creatividad!",
        // Seccion bebidas
        bebidasTitulo: "BEBIDAS",
        limonadaTitulo: "Jarra de limonada",
        limonadaDesc: "Jarra de limonada x 1lt. con menta y jengibre, ideal para acompañar mariscos. Equilibra la acidez del limón con la frescura de la menta y el toque picante del jengibre.",
        seleccionarLimonada: "Seleccionar limonada",
        cantidad: "Cantidad:",
        vinoBlancoTitulo: "Vino Blanco",
        vinoBlancoDesc: "Vino blanco Chenin Blanc botella de 3/4 lt. Fresco y afrutado, perfecto para mariscos. Su carácter ligero y notas cítricas realzan los sabores del mar.",
        seleccionarVinoBlanco: "Seleccionar vino blanco",
        vinoTintoTitulo: "Vino Tinto",
        vinoTintoDesc: "Vino tinto Malbec botella de 3/4 lt., con su cuerpo medio y taninos suaves, ofrece un contraste audaz pero equilibrado que complementan los sabores del mar.",
        seleccionarVinoTinto: "Seleccionar vino tinto",
        miPedido: "Mi Pedido",
        //seccion entradas
        entradasTitulo: "ENTRADAS",
        brusquetasTitulo: "Bruschettas",
        brusquetasDesc: "Bruschettas con exquisita mezcla mediterránea de palta cremosa, queso crema suave, aceitunas negras jugosas y albahaca fresca. Una explosión de sabores y texturas en cada bocado, perfecta para abrir el apetito con un toque gourmet.",
        seleccionarBrusquetas: "Seleccionar brusquetas",
        cantidad: "Cantidad:",
        empanadasTitulo: "Empanadas de mariscos",
        empanadasDesc: "Empanadas de salmón, un festín marino en cada bocado. El jugoso salmón se combina con ingredientes selectos, envuelto en una masa dorada y crujiente. Un deleite para los amantes del pescado, ofreciendo un sabor ahumado y delicado en cada deliciosa mordida.",
        seleccionarEmpanadas: "Seleccionar empanadas",
        ensaladaTitulo: "Ensalada de mariscos",
        ensaladaDesc: "Ensalada de mariscos y calamares, una fusión fresca del océano en tu plato. Los jugosos calamares se entrelazan con una variedad de mariscos, bañados en aderezo ligero y adornados con vegetales frescos.",
        seleccionarEnsalada: "Seleccionar ensalada de mariscos",
        //seccion Platos
        platosTitulo: "PLATOS",
        langostinosTitulo: "Langostinos con salsa de camarones",
        langostinosDesc: "Un plato exquisito de langostinos bañados en una salsa cremosa de camarones. Los langostinos jugosos se combinan con una salsa rica y suave, realzada con el sabor a mar de los camarones. Una delicia indulgente que deleitará los paladares más exigentes con su exquisita combinación de sabores marinos.",
        seleccionarLangostinos: "Seleccionar langostinos",
        cantidad: "Cantidad:",
        mejillonesTitulo: "Mejillones al ajillo",
        mejillonesDesc: "Un plato vibrante de mejillones al ajillo, ofreciendo una explosión de sabores mediterráneos. Los mejillones frescos se cocinan en una salsa de ajo y aceite de oliva, impregnando cada bocado con su aroma y sabor intensos. Una experiencia culinaria irresistible que te transportará a las costas de España con cada mordisco.",
        seleccionarMejillones: "Seleccionar mejillones",
        rabasTitulo: "Rabas rebozadas",
        rabasDesc: "Deliciosas rabas rebozadas, crujientes por fuera y tiernas por dentro, acompañadas de una salsa de mostaza con un toque picante. El rebozado dorado resalta el sabor suave y jugoso de las rabas, mientras que la salsa de mostaza añade un toque audaz y delicioso. Un placer irresistible para los amantes de la cocina gourmet.",
        seleccionarRabas: "Seleccionar rabas",
        //Seccion postres
        postresTitulo: "POSTRES",
        tiramisuTitulo: "Tiramisú",
        tiramisuDesc: "Un clásico italiano, indulgente y reconfortante. Capas de bizcochuelo empapados en café, alternadas con una mezcla cremosa de mascarpone, huevos y coronado con cacao en polvo.",
        seleccionarTiramisu: "Seleccionar Tiramisú",
        cantidad: "Cantidad:",
        higosTitulo: "Higos en Almíbar",
        higosDesc: "Higos en almíbar suave y aromático, que resalta su sabor natural y los hace aún más indulgentes. Perfectos como postre o acompañamiento.",
        seleccionarHigos: "Seleccionar Higos en Almíbar",
        brownieTitulo: "Brownie con Crema",
        brownieDesc: "Un tentador corazón de chocolate decadente y una textura densa y suave. Coronado con una generosa porción de helado de crema sobre el brownie tibio, creando una combinación perfecta.",
        seleccionarBrownie: "Seleccionar Brownie con Crema",
        //Seccion Contacto
        nombre: "Nombre:",
        correoElectronico: "Correo Electrónico:",
        telefono: "Teléfono:",
        mensaje: "Mensaje:",
        ubicacion: "Nuestra ubicación:",
        formularioContacto: "Formulario de Contacto",
        enviar: "Enviar",
        //Seccion mi pedido
        ordentitulo: "MI PEDIDO",
        mesanumero: "Mesa numero:",
        name: "Nombre:",
        bebidaspedido: "Bebidas",
        bebidasseleccionadas: "Aca iria lo que se selecciono de bebida",
        entradaspedido: "Entradas",
        entradasseleccionadas: "Aca iria lo que se selecciono de entrada.",
        platospedidos: "Platos",
        platossleccionados: "Aca iria lo que se selecciono de plato.",
        postrespedidos: "Postres",
        postresseleccionados: "Aca iria lo que se selecciono de postre",
        submitorder: "Enviar Pedido",

    },
    en: {
        entradas: "STARTERS",
        platos: "MAIN COURSES",
        postres: "DESSERTS",
        bebidas: "DRINKS",
        contacto: "CONTACT",
        welcomeTitle: "Welcome to Mar de Luna",
        welcomeMessage: "At Mar de Luna, we pride ourselves on offering a unique culinary experience, where each dish reflects our commitment to excellence and the authentic taste of the sea. With a history rooted in a passion for cooking and respect for fresh, quality ingredients, we have built a legacy that distinguishes us in the culinary world.",
        valuesTitle: "Our Values:",
        quality: "Quality: We strive to offer fresh and carefully selected seafood with the highest standard of quality in each of our dishes.",
        professionalism: "Professionalism: Our team is composed of experts in the culinary arts, committed to perfection in every detail and the satisfaction of our diners.",
        tradition: "Tradition: With decades of experience in preparing marine delicacies, we honor culinary tradition and celebrate the richness of flavors that the sea offers us.",
        experience: "Welcome to an unforgettable culinary experience at Mar de Luna!",
        chefMessage: "Hello! I am Francis Gollum, the executive chef at Mar de Luna. My passion is to create culinary experiences that celebrate the flavors of the sea. Join me on a gastronomic journey where each dish tells a story of freshness and creativity!",
        // Seccion bebidas
        bebidasTitulo: "DRINKS",
        limonadaTitulo: "Lemonade Jug",
        limonadaDesc: "Lemonade jug 1lt. with mint and ginger, ideal to accompany seafood. Balances the acidity of the lemon with the freshness of mint and the spicy touch of ginger.",
        seleccionarLimonada: "Select lemonade",
        cantidad: "Quantity:",
        vinoBlancoTitulo: "White Wine",
        vinoBlancoDesc: "Chenin Blanc white wine 3/4 lt. Fresh and fruity, perfect for seafood. Its light character and citrus notes enhance the flavors of the sea.",
        seleccionarVinoBlanco: "Select white wine",
        vinoTintoTitulo: "Red Wine",
        vinoTintoDesc: "Malbec red wine 3/4 lt., with its medium body and soft tannins, offers a bold yet balanced contrast that complements the flavors of the sea.",
        seleccionarVinoTinto: "Select red wine",
        miPedido: "My Order",
        //seccion entradas
        entradasTitulo: "STARTERS",
        brusquetasTitulo: "Bruschettas",
        brusquetasDesc: "Bruschettas with an exquisite Mediterranean mix of creamy avocado, soft cream cheese, juicy black olives, and fresh basil. An explosion of flavors and textures in every bite, perfect for whetting your appetite with a gourmet touch.",
        seleccionarBrusquetas: "Select bruschettas",
        cantidad: "Quantity:",
        empanadasTitulo: "Seafood empanadas",
        empanadasDesc: "Salmon empanadas, a marine feast in every bite. The juicy salmon is combined with select ingredients, wrapped in a golden, crispy dough. A delight for fish lovers, offering a smoky and delicate flavor in every delicious bite.",
        seleccionarEmpanadas: "Select empanadas",
        ensaladaTitulo: "Seafood salad",
        ensaladaDesc: "Seafood and squid salad, a fresh ocean fusion on your plate. Juicy squids intertwine with a variety of seafood, bathed in light dressing and adorned with fresh vegetables.",
        seleccionarEnsalada: "Select seafood salad",
        //Seccion platos
        platosTitulo: "DISHES",
        langostinosTitulo: "Prawns with Shrimp Sauce",
        langostinosDesc: "An exquisite dish of prawns bathed in a creamy shrimp sauce. Juicy prawns are combined with a rich and smooth sauce, enhanced by the sea flavor of the shrimp. An indulgent delight that will delight even the most discerning palates with its exquisite combination of marine flavors.",
        seleccionarLangostinos: "Select prawns",
        cantidad: "Quantity:",
        mejillonesTitulo: "Garlic Mussels",
        mejillonesDesc: "A vibrant dish of garlic mussels, offering an explosion of Mediterranean flavors. Fresh mussels are cooked in a garlic and olive oil sauce, infusing each bite with their intense aroma and flavor. An irresistible culinary experience that will transport you to the shores of Spain with every bite.",
        seleccionarMejillones: "Select mussels",
        rabasTitulo: "Breaded Squid",
        rabasDesc: "Delicious breaded squid rings, crispy on the outside and tender on the inside, served with a spicy mustard sauce. The golden breading highlights the soft and juicy flavor of the squid, while the mustard sauce adds a bold and delicious touch. An irresistible pleasure for lovers of gourmet cuisine.",
        seleccionarRabas: "Select squid",
        //Seccion postre
        postresTitulo: "DESSERTS",
        tiramisuTitulo: "Tiramisu",
        tiramisuDesc: "A classic Italian dessert, indulgent and comforting. Layers of sponge cake soaked in coffee, alternating with a creamy mixture of mascarpone, eggs, and topped with cocoa powder.",
        seleccionarTiramisu: "Select tiramisu",
        cantidad: "Quantity:",
        higosTitulo: "Figs in syrup",
        higosDesc: "Figs in smooth and aromatic syrup, highlighting their natural flavor and making them even more indulgent. Perfect as a dessert or accompaniment.",
        seleccionarHigos: "Select figs in syrup",
        brownieTitulo: "Brownie with cream",
        brownieDesc: "A tempting heart of decadent chocolate and a dense, soft texture. Topped with a generous scoop of cream ice cream on warm brownie, creating a perfect combination.",
        seleccionarBrownie: "Select brownie with cream",
        //Seccion contacto
        formularioContacto: "Contact Form",
        nombre: "Name:",
        correoElectronico: "Email:",
        telefono: "Phone:",
        mensaje: "Message:",
        ubicacion: "Our Location:",
        enviar: "Send",
        //Seccion mi pedido
        ordentitulo: "MY ORDER",
        mesanumero: "Table number:",
        name: "Name:",
        bebidaspedido: "Drinks",
        bebidasseleccionadas: "Here would go what was selected from the drink",
        entradaspedido: "Appetizers",
        entradasseleccionadas: "Here would go what was selected from the appetizer.",
        platospedidos: "Main Courses",
        platossleccionados: "Here would go what was selected from the main course.",
        postrespedidos: "Desserts",
        postresseleccionados: "Here would go what was selected from the dessert",
        submitorder: "Submit Order",
        
    },
    pt: {
        entradas: "ENTRADAS",
        platos: "PRATOS PRINCIPAIS",
        postres: "SOBREMESAS",
        bebidas: "BEBIDAS",
        contacto: "CONTATO",
        welcomeTitle: "Bem-vindos ao Mar de Luna",
        welcomeMessage: "No Mar de Luna, temos orgulho de oferecer uma experiência culinária única, onde cada prato reflete nosso compromisso com a excelência e o sabor autêntico do mar. Com uma trajetória enraizada na paixão pela cozinha e no respeito pelos ingredientes frescos e de qualidade, construímos um legado que nos distingue no mundo gastronômico.",
        valuesTitle: "Nossos Valores:",
        quality: "Qualidade: Esforçamo-nos para oferecer frutos do mar frescos e selecionados com o mais alto padrão de qualidade em cada um dos nossos pratos.",
        professionalism: "Profissionalismo: Nossa equipe é composta por especialistas na arte culinária, comprometidos com a perfeição em cada detalhe e com a satisfação dos nossos clientes.",
        tradition: "Tradicional: Com décadas de experiência na preparação de delícias marinhas, honramos a tradição culinária e celebramos a riqueza de sabores que o mar nos oferece.",
        experience: "Bem-vindos a uma experiência gastronômica inesquecível no Mar de Luna!",
        chefMessage: "Olá! Sou Francis Gollum, o chef executivo do Mar de Luna. Minha paixão é criar experiências culinárias que celebram os sabores do mar. Junte-se a mim em uma jornada gastronômica onde cada prato conta uma história de frescor e criatividade!",
        //Seccion bebidas
        bebidasTitulo: "BEBIDAS",
        limonadaTitulo: "Jarra de limonada",
        limonadaDesc: "Jarra de limonada de 1 litro com hortelã e gengibre, ideal para acompanhar frutos do mar. Equilibra a acidez do limão com a frescura da hortelã e o toque picante do gengibre.",
        seleccionarLimonada: "Selecionar limonada",
        cantidad: "Quantidade:",
        vinoBlancoTitulo: "Vinho Branco",
        vinoBlancoDesc: "Vinho branco Chenin Blanc garrafa de 3/4 litro. Fresco e frutado, perfeito para frutos do mar. Seu caráter leve e notas cítricas realçam os sabores do mar.",
        seleccionarVinoBlanco: "Selecionar vinho branco",
        vinoTintoTitulo: "Vinho Tinto",
        vinoTintoDesc: "Vinho tinto Malbec garrafa de 3/4 litro, com seu corpo médio e taninos suaves, oferece um contraste ousado mas equilibrado que complementa os sabores do mar.",
        seleccionarVinoTinto: "Selecionar vinho tinto",
        miPedido: "Meu Pedido",
        //Seccion entradas
        entradasTitulo: "ENTRADAS",
        brusquetasTitulo: "Bruschettas",
        brusquetasDesc: "Bruschettas com uma mistura mediterrânea de abacate cremoso, queijo cremoso suave, azeitonas pretas suculentas e manjericão fresco. Uma explosão de sabores e texturas em cada mordida, perfeita para abrir o apetite com um toque gourmet.",
        seleccionarBrusquetas: "Selecionar bruschettas",
        cantidad: "Quantidade:",
        empanadasTitulo: "Empanadas de mariscos",
        empanadasDesc: "Empanadas de salmão, um festim marinho em cada mordida. O salmão suculento é combinado com ingredientes selecionados, envoltos em uma massa dourada e crocante. Um deleite para os amantes de peixe, oferecendo um sabor defumado e delicado em cada deliciosa mordida.",
        seleccionarEmpanadas: "Selecionar empanadas",
        ensaladaTitulo: "Salada de frutos do mar",
        ensaladaDesc: "Salada de frutos do mar e lulas, uma fusão fresca do oceano no seu prato. As lulas suculentas se entrelaçam com uma variedade de frutos do mar, banhados em um molho leve e adornados com vegetais frescos.",
        seleccionarEnsalada: "Selecionar salada de frutos do mar",
        //Seccion platos
        platosTitulo: "PRATOS",
        langostinosTitulo: "Langostinos com molho de camarão",
        langostinosDesc: "Um prato requintado de langostinos banhados em um molho cremoso de camarão. Os langostinos suculentos se combinam com um molho rico e suave, realçado com o sabor a mar dos camarões. Uma delícia indulgente que encantará os paladares mais exigentes com sua combinação requintada de sabores marinhos.",
        seleccionarLangostinos: "Selecionar langostinos",
        cantidad: "Quantidade:",
        mejillonesTitulo: "Mexilhões ao alho",
        mejillonesDesc: "Um prato vibrante de mexilhões ao alho, oferecendo uma explosão de sabores mediterrâneos. Os mexilhões frescos são cozidos em um molho de alho e azeite, impregnando cada mordida com seu aroma e sabor intensos. Uma experiência culinária irresistível que o transportará às costas da Espanha a cada mordida.",
        seleccionarMejillones: "Selecionar mexilhões",
        rabasTitulo: "Rabas empanadas",
        rabasDesc: "Deliciosas rabas empanadas, crocantes por fora e macias por dentro, acompanhadas de um molho de mostarda com um toque picante. A massa dourada realça o sabor suave e suculento das rabas, enquanto o molho de mostarda adiciona um toque audacioso e delicioso. Um prazer irresistível para os amantes da culinária gourmet.",
        seleccionarRabas: "Selecionar rabas",
        //Seccion postres
        postresTitulo: "SOBREMESAS",
        tiramisuTitulo: "Tiramisú",
        tiramisuDesc: "Um clássico italiano, indulgente e reconfortante. Camadas de bolo embebido em café, alternadas com uma mistura cremosa de mascarpone, ovos e polvilhadas com cacau em pó.",
        seleccionarTiramisu: "Selecionar Tiramisú",
        cantidad: "Quantidade:",
        higosTitulo: "Figos em Calda",
        higosDesc: "Figos em calda suave e aromática, realçando seu sabor natural e tornando-os ainda mais indulgentes. Perfeitos como sobremesa ou acompanhamento.",
        seleccionarHigos: "Selecionar Figos em Calda",
        brownieTitulo: "Brownie com Creme",
        brownieDesc: "Um tentador coração de chocolate decadente e uma textura densa e macia. Coroado com uma generosa porção de sorvete de creme sobre o brownie morno, criando uma combinação perfeita.",
        seleccionarBrownie: "Selecionar Brownie com Creme",
        //Seccion contacto
        nombre: "Nome:",
        correoElectronico: "E-mail:",
        telefono: "Telefone:",
        mensaje: "Mensagem:",
        ubicacion: "Nossa localização:",
        formularioContacto: "Formulário de Contato",
        enviar: "Enviarenviar",
        //Seccion mi pedido
        ordentitulo: "MEU PEDIDO",
        mesanumero: "Número da mesa:",
        name: "Nome:",
        bebidaspedido: "Bebidas",
        bebidasseleccionadas: "Aqui iria o que foi selecionado da bebida",
        entradaspedido: "Entradas",
        entradasseleccionadas: "Aqui iria o que foi selecionado de entrada.",
        platospedidos: "Pratos",
        platossleccionados: "Aqui iria o que foi selecionado de prato.",
        postrespedidos: "Sobremesas",
        postresseleccionados: "Aqui iria o que foi selecionado de sobremesa",
        submitorder: "Enviar Pedido",
    },
    it: {
        entradas: "ANTIPASTI",
        platos: "PIATTI PRINCIPALI",
        postres: "DOLCI",
        bebidas: "BIBITE",
        contacto: "CONTATTI",
        welcomeTitle: "Benvenuti a Mar de Luna",
        welcomeMessage: "A Mar de Luna, siamo orgogliosi di offrire un'esperienza culinaria unica, in cui ogni piatto riflette il nostro impegno per l'eccellenza e il gusto autentico del mare. Con una storia radicata nella passione per la cucina e nel rispetto per gli ingredienti freschi e di qualità, abbiamo costruito un'eredità che ci distingue nel mondo gastronomico.",
        valuesTitle: "I nostri valori:",
        quality: "Qualità: Ci sforziamo di offrire frutti di mare freschi e selezionati con il massimo standard di qualità in ciascuno dei nostri piatti.",
        professionalism: "Professionalità: Il nostro team è composto da esperti nelle arti culinarie, impegnati nella perfezione in ogni dettaglio e nella soddisfazione dei nostri commensali.",
        tradition: "Tradizione: Con decenni di esperienza nella preparazione di delizie marine, onoriamo la tradizione culinaria e celebriamo la ricchezza di sapori che il mare ci offre.",
        experience: "Benvenuti in un'esperienza culinaria indimenticabile da Mar de Luna!",
        chefMessage: "Ciao! Sono Francis Gollum, lo chef esecutivo di Mar de Luna. La mia passione è creare esperienze culinarie che celebrano i sapori del mare. Unisciti a me in un viaggio gastronomico in cui ogni piatto racconta una storia di freschezza e creatività!",
        //Seccion bebidas
        bebidasTitulo: "BIBITE",
        limonadaTitulo: "Caraffa di limonata",
        limonadaDesc: "Caraffa di limonata da 1 litro con menta e zenzero, ideale per accompagnare i frutti di mare. Bilancia l'acidità del limone con la freschezza della menta e il tocco piccante dello zenzero.",
        seleccionarLimonada: "Selezionare limonata",
        cantidad: "Quantità:",
        vinoBlancoTitulo: "Vino Bianco",
        vinoBlancoDesc: "Vino bianco Chenin Blanc bottiglia da 3/4 litro. Fresco e fruttato, perfetto per i frutti di mare. Il suo carattere leggero e le note agrumate esaltano i sapori del mare.",
        seleccionarVinoBlanco: "Selezionare vino bianco",
        vinoTintoTitulo: "Vino Rosso",
        vinoTintoDesc: "Vino rosso Malbec bottiglia da 3/4 litro, con il suo corpo medio e tannini morbidi, offre un contrasto audace ma equilibrato che completa i sapori del mare.",
        seleccionarVinoTinto: "Selezionare vino rosso",
        miPedido: "Il mio Ordine",
        //Seccion entradas
        entradasTitulo: "ANTIPASTI",
        brusquetasTitulo: "Bruschette",
        brusquetasDesc: "Bruschette con squisita miscela mediterranea di avocado cremoso, formaggio cremoso morbido, olive nere succose e basilico fresco. Un'esplosione di sapori e consistenze in ogni boccone, perfetta per aprire l'appetito con un tocco gourmet.",
        seleccionarBrusquetas: "Selezionare bruschette",
        cantidad: "Quantità:",
        empanadasTitulo: "Empanadas di mare",
        empanadasDesc: "Empanadas di salmone, una festa marina in ogni boccone. Il salmone succoso si combina con ingredienti selezionati, avvolto in una pasta dorata e croccante. Una delizia per gli amanti del pesce, offrendo un sapore affumicato e delicato in ogni delizioso morso.",
        seleccionarEmpanadas: "Selezionare empanadas",
        ensaladaTitulo: "Insalata di mare",
        ensaladaDesc: "Insalata di mare e calamari, una fresca fusione dell'oceano nel tuo piatto. I calamari succosi si intrecciano con una varietà di frutti di mare, conditi con una leggera vinaigrette e guarniti con verdure fresche.",
        seleccionarEnsalada: "Selezionare insalata di mare",
        //Seccion platos
        platosTitulo: "PIATTI",
        langostinosTitulo: "Gamberoni con salsa di gamberetti",
        langostinosDesc: "Un piatto squisito di gamberoni bagnati in una salsa cremosa di gamberetti. I gamberoni succulenti si combinano con una salsa ricca e morbida, esaltata dal sapore del mare dei gamberetti. Una delizia indulgente che delizierà i palati più esigenti con la sua squisita combinazione di sapori marini.",
        seleccionarLangostinos: "Seleziona gamberoni",
        cantidad: "Quantità:",
        mejillonesTitulo: "Cozze all'aglio",
        mejillonesDesc: "Un piatto vibrante di cozze all'aglio, che offre un'esplosione di sapori mediterranei. Le cozze fresche sono cotte in una salsa di aglio e olio d'oliva, che impregna ogni morso con il suo aroma e sapore intensi. Un'esperienza culinaria irresistibile che ti trasporterà lungo le coste della Spagna con ogni morso.",
        seleccionarMejillones: "Seleziona cozze",
        rabasTitulo: "Calamari impanati",
        rabasDesc: "Deliziosi anelli di calamari impanati, croccanti all'esterno e morbidi all'interno, serviti con una salsa di senape piccante. La panatura dorata enfatizza il gusto morbido e succulento dei calamari, mentre la salsa di senape aggiunge una nota audace e deliziosa. Un piacere irresistibile per gli amanti della cucina gourmet.",
        seleccionarRabas: "Seleziona calamari",
        //Seccion postre
        postresTitulo: "DOLCI",
        tiramisuTitulo: "Tiramisù",
        tiramisuDesc: "Un classico italiano, indulgente e confortante. Strati di pan di spagna inzuppati nel caffè, alternati a una crema di mascarpone, uova e cacao in polvere.",
        seleccionarTiramisu: "Seleziona Tiramisù",
        cantidad: "Quantità:",
        higosTitulo: "Fichi in Sciroppo",
        higosDesc: "Fichi in sciroppo morbido e aromatico, che esaltano il loro sapore naturale e li rendono ancora più indulgenti. Perfetti come dessert o accompagnamento.",
        seleccionarHigos: "Seleziona Fichi in Sciroppo",
        brownieTitulo: "Brownie con Panna",
        brownieDesc: "Un invitante cuore di cioccolato decadente e una consistenza densa e morbida. Guarnito con una generosa porzione di gelato alla panna sul brownie tiepido, creando una combinazione perfetta.",
        seleccionarBrownie: "Seleziona Brownie con Panna",
        //Seccion contacto
        formularioContacto: "Modulo di contatto",
        nombre: "Nome:",
        correoElectronico: "E-mail:",
        telefono: "Telefono:",
        mensaje: "Messaggio:",
        ubicacion: "La nostra posizione:",
        //Seccion mi pedido
        ordentitulo: "IL MIO ORDINE",
        mesanumero: "Numero del tavolo:",
        name: "Nome:",
        bebidaspedido: "Bevande",
        bebidasseleccionadas: "Qui andrebbe quello che è stato selezionato dalla bevanda",
        entradaspedido: "Antipasti",
        entradasseleccionadas: "Qui andrebbe quello che è stato selezionato dall'antipasto.",
        platospedidos: "Piatti",
        platossleccionados: "Qui andrebbe quello che è stato selezionato dal piatto.",
        postrespedidos: "Dolci",
        postresseleccionados: "Qui andrebbe quello che è stato selezionato dal dolce",
        submitorder: "Invia Ordine",
    },
    de: {
        entradas: "VORSPEISEN",
        platos: "HAUPTGERICHTE",
        postres: "NACHTISCHE",
        bebidas: "GETRÄNKE",
        contacto: "KONTAKT",
        welcomeTitle: "Willkommen bei Mar de Luna",
        welcomeMessage: "Bei Mar de Luna sind wir stolz darauf, ein einzigartiges kulinarisches Erlebnis zu bieten, bei dem jedes Gericht unser Engagement für Exzellenz und den authentischen Geschmack des Meeres widerspiegelt. Mit einer Geschichte, die in einer Leidenschaft für das Kochen und dem Respekt für frische, hochwertige Zutaten verwurzelt ist, haben wir ein Erbe aufgebaut, das uns in der kulinarischen Welt auszeichnet.",
        valuesTitle: "Unsere Werte:",
        quality: "Qualität: Wir bemühen uns, frische und sorgfältig ausgewählte Meeresfrüchte mit dem höchsten Qualitätsstandard in jedem unserer Gerichte anzubieten.",
        professionalism: "Professionalität: Unser Team besteht aus Experten der kulinarischen Künste, die sich der Perfektion in jedem Detail und der Zufriedenheit unserer Gäste verpflichtet fühlen.",
        tradition: "Tradition: Mit jahrzehntelanger Erfahrung in der Zubereitung von Meeresdelikatessen ehren wir die kulinarische Tradition und feiern die Reichtum an Aromen, die das Meer uns bietet.",
        experience: "Willkommen zu einem unvergesslichen kulinarischen Erlebnis bei Mar de Luna!",
        chefMessage: "Hallo! Ich bin Francis Gollum, der Küchenchef bei Mar de Luna. Meine Leidenschaft ist es, kulinarische Erlebnisse zu schaffen, die die Aromen des Meeres feiern. Begleiten Sie mich auf eine gastronomische Reise, bei der jedes Gericht eine Geschichte von Frische und Kreativität erzählt!",
        // Seccion bebidas
        bebidasTitulo: "GETRÄNKE",
        limonadaTitulo: "Limonadenkrug",
        limonadaDesc: "Limonadenkrug 1lt. mit Minze und Ingwer, ideal für Meeresfrüchte. Balanciert die Säure der Zitrone mit der Frische der Minze und der scharfen Note des Ingwers.",
        seleccionarLimonada: "Limonade wählen",
        cantidad: "Menge:",
        vinoBlancoTitulo: "Weißwein",
        vinoBlancoDesc: "Chenin Blanc Weißwein 3/4 lt. Frisch und fruchtig, perfekt für Meeresfrüchte. Sein leichter Charakter und Zitrusnoten verstärken die Aromen des Meeres.",
        seleccionarVinoBlanco: "Weißwein wählen",
        vinoTintoTitulo: "Rotwein",
        vinoTintoDesc: "Malbec Rotwein 3/4 lt., mit seinem mittleren Körper und weichen Tanninen, bietet einen mutigen, aber ausgewogenen Kontrast, der die Aromen des Meeres ergänzt.",
        seleccionarVinoTinto: "Rotwein wählen",
        miPedido: "Meine Bestellung",
        //Seccion entradas
        entradasTitulo: "VORSPEISEN",
        brusquetasTitulo: "Bruschettas",
        brusquetasDesc: "Bruschettas mit einer exquisiten mediterranen Mischung aus cremiger Avocado, weichem Frischkäse, saftigen schwarzen Oliven und frischem Basilikum. Eine Explosion von Aromen und Texturen in jedem Bissen, perfekt, um den Appetit mit einem Gourmet-Touch zu wecken.",
        seleccionarBrusquetas: "Bruschettas wählen",
        cantidad: "Menge:",
        empanadasTitulo: "Meeresfrüchte-Empanadas",
        empanadasDesc: "Lachsempanadas, ein maritimes Fest in jedem Bissen. Der saftige Lachs wird mit ausgewählten Zutaten kombiniert, in einen goldenen, knusprigen Teig gewickelt. Ein Genuss für Fischliebhaber, der in jedem köstlichen Bissen einen rauchigen und zarten Geschmack bietet.",
        seleccionarEmpanadas: "Empanadas wählen",
        ensaladaTitulo: "Meeresfrüchtesalat",
        ensaladaDesc: "Meeresfrüchtesalat mit Tintenfisch, eine frische Ozean-Fusion auf Ihrem Teller. Saftige Tintenfische verbinden sich mit einer Vielzahl von Meeresfrüchten, gebadet in leichtem Dressing und garniert mit frischem Gemüse.",
        seleccionarEnsalada: "Meeresfrüchtesalat wählen",
        //Seccion platos
        platosTitulo: "GERICHTE",
        langostinosTitulo: "Krabben mit Garnelensauce",
        langostinosDesc: "Ein exquisites Gericht aus Krabben in einer cremigen Garnelensauce. Die saftigen Krabben werden mit einer reichen und weichen Sauce kombiniert, die durch den Geschmack des Meeres der Garnelen verfeinert wird. Eine köstliche Gaumenfreude, die selbst die anspruchsvollsten Geschmacksnerven mit ihrer exquisiten Kombination von Meeresaromen begeistern wird.",
        seleccionarLangostinos: "Krabben auswählen",
        cantidad: "Menge:",
        mejillonesTitulo: "Knoblauchmuscheln",
        mejillonesDesc: "Ein lebhaftes Gericht mit Knoblauchmuscheln, das eine Explosion mediterraner Aromen bietet. Frische Muscheln werden in einer Sauce aus Knoblauch und Olivenöl gekocht und durchdringen jeden Bissen mit ihrem intensiven Aroma und Geschmack. Ein unwiderstehliches kulinarisches Erlebnis, das Sie mit jedem Bissen an die Küsten Spaniens entführt.",
        seleccionarMejillones: "Muscheln auswählen",
        rabasTitulo: "Panierter Tintenfisch",
        rabasDesc: "Köstliche panierte Tintenfischringe, außen knusprig und innen zart, serviert mit einer würzigen Senfsauce. Die goldene Panade betont den sanften und saftigen Geschmack der Tintenfischringe, während die Senfsauce eine kühne und köstliche Note hinzufügt. Ein unwiderstehliches Vergnügen für Liebhaber der Gourmetküche.",
        seleccionarRabas: "Tintenfisch auswählen",
        //Seccion postre
        postresTitulo: "NACHSPEISEN",
        tiramisuTitulo: "Tiramisu",
        tiramisuDesc: "Ein klassisches italienisches Dessert, genussvoll und tröstlich. Schichten von Biskuit in Kaffee getränkt, abwechselnd mit einer cremigen Mischung aus Mascarpone, Eiern und bestäubt mit Kakaopulver.",
        seleccionarTiramisu: "Tiramisu auswählen",
        cantidad: "Menge:",
        higosTitulo: "Feigen in Sirup",
        higosDesc: "Feigen in glattem und aromatischem Sirup, die ihren natürlichen Geschmack hervorheben und sie noch köstlicher machen. Perfekt als Dessert oder Beilage.",
        seleccionarHigos: "Feigen in Sirup auswählen",
        brownieTitulo: "Brownie mit Sahne",
        brownieDesc: "Ein verlockendes Herz aus dekadenter Schokolade und einer dichten, weichen Textur. Getoppt mit einer großzügigen Kugel Sahneeis auf warmem Brownie, für eine perfekte Kombination.",
        seleccionarBrownie: "Brownie mit Sahne auswählen", 
        //Seccion contacto
        formularioContacto: "Kontaktformular",
        nombre: "Name:",
        correoElectronico: "E-Mail:",
        telefono: "Telefon:",
        mensaje: "Nachricht:",
        ubicacion: "Unser Standort:",
        //Seccion mi pedido
        ordentitulo: "MEINE BESTELLUNG",
        mesanumero: "Tischnummer:",
        name: "Name:",
        bebidaspedido: "Getränke",
        bebidasseleccionadas: "Hier würde das, was aus dem Getränk ausgewählt wurde, hingehen",
        entradaspedido: "Vorspeisen",
        entradasseleccionadas: "Hier würde das, was aus der Vorspeise ausgewählt wurde, hingehen.",
        platospedidos: "Hauptgerichte",
        platossleccionados: "Hier würde das, was aus dem Hauptgericht ausgewählt wurde, hingehen.",
        postrespedidos: "Desserts",
        postresseleccionados: "Hier würde das, was aus dem Dessert ausgewählt wurde, hingehen",
        submitorder: "Bestellung Absenden",
        
    },
    fr: {
        entradas: "ENTRÉES",
        platos: "PLATS PRINCIPAUX",
        postres: "DESSERTS",
        bebidas: "BOISSONS",
        contacto: "CONTACT",
        welcomeTitle: "Bienvenue chez Mar de Luna",
        welcomeMessage: "Chez Mar de Luna, nous sommes fiers d'offrir une expérience culinaire unique, où chaque plat reflète notre engagement envers l'excellence et le goût authentique de la mer. Avec une histoire enracinée dans la passion pour la cuisine et le respect des ingrédients frais et de qualité, nous avons construit un héritage qui nous distingue dans le monde culinaire.",
        valuesTitle: "Nos valeurs:",
        quality: "Qualité: Nous nous efforçons d'offrir des fruits de mer frais et soigneusement sélectionnés avec le plus haut standard de qualité dans chacun de nos plats.",
        professionalism: "Professionnalisme: Notre équipe est composée d'experts en arts culinaires, engagés dans la perfection dans les moindres détails et la satisfaction de nos convives.",
        tradition: "Tradition: Avec des décennies d'expérience dans la préparation de délices marins, nous honorons la tradition culinaire et célébrons la richesse des saveurs que la mer nous offre.",
        experience: "Bienvenue à une expérience culinaire inoubliable chez Mar de Luna!",
        chefMessage: "Bonjour! Je suis Francis Gollum, le chef exécutif chez Mar de Luna. Ma passion est de créer des expériences culinaires qui célèbrent les saveurs de la mer. Rejoignez-moi dans un voyage gastronomique où chaque plat raconte une histoire de fraîcheur et de créativité!",
        // Seccion bebidas
        bebidasTitulo: "BOISSONS",
        limonadaTitulo: "Pichet de limonade",
        limonadaDesc: "Pichet de limonade 1lt. avec menthe et gingembre, idéal pour accompagner les fruits de mer. Équilibre l'acidité du citron avec la fraîcheur de la menthe et la touche épicée du gingembre.",
        seleccionarLimonada: "Sélectionner limonade",
        cantidad: "Quantité:",
        vinoBlancoTitulo: "Vin Blanc",
        vinoBlancoDesc: "Vin blanc Chenin Blanc bouteille de 3/4 lt. Frais et fruité, parfait pour les fruits de mer. Son caractère léger et ses notes d'agrumes rehaussent les saveurs de la mer.",
        seleccionarVinoBlanco: "Sélectionner vin blanc",
        vinoTintoTitulo: "Vin Rouge",
        vinoTintoDesc: "Vin rouge Malbec bouteille de 3/4 lt., avec son corps moyen et ses tanins doux, offre un contraste audacieux mais équilibré qui complète les saveurs de la mer.",
        seleccionarVinoTinto: "Sélectionner vin rouge",
        miPedido: "Ma Commande",
        //Seccion entradas
        entradasTitulo: "ENTRÉES",
        brusquetasTitulo: "Bruschettas",
        brusquetasDesc: "Bruschettas avec un mélange méditerranéen exquis d'avocat crémeux, de fromage à la crème doux, d'olives noires juteuses et de basilic frais. Une explosion de saveurs et de textures à chaque bouchée, parfaite pour ouvrir l'appétit avec une touche gastronomique.",
        seleccionarBrusquetas: "Sélectionner bruschettas",
        cantidad: "Quantité:",
        empanadasTitulo: "Empanadas de fruits de mer",
        empanadasDesc: "Empanadas de saumon, une fête marine à chaque bouchée. Le saumon juteux est combiné avec des ingrédients sélectionnés, enveloppés dans une pâte dorée et croustillante. Un délice pour les amateurs de poisson, offrant une saveur fumée et délicate à chaque bouchée délicieuse.",
        seleccionarEmpanadas: "Sélectionner empanadas",
        ensaladaTitulo: "Salade de fruits de mer",
        ensaladaDesc: "Salade de fruits de mer et calamars, une fusion fraîche de l'océan dans votre assiette. Les calamars juteux se mêlent à une variété de fruits de mer, baignés dans une vinaigrette légère et garnis de légumes frais.",
        seleccionarEnsalada: "Sélectionner salade de fruits de mer",
        //Seccion platos
        platosTitulo: "PLATS",
        langostinosTitulo: "Langoustines à la sauce aux crevettes",
        langostinosDesc: "Un plat exquis de langoustines nappées d'une sauce crémeuse aux crevettes. Les langoustines juteuses se marient à une sauce riche et onctueuse, rehaussée par la saveur marine des crevettes. Un délice indulgent qui ravira les palais les plus exigeants avec son mariage exquis de saveurs marines.",
        seleccionarLangostinos: "Sélectionner les langoustines",
        cantidad: "Quantité :",
        mejillonesTitulo: "Moules à l'ail",
        mejillonesDesc: "Un plat vibrant de moules à l'ail, offrant une explosion de saveurs méditerranéennes. Les moules fraîches sont cuites dans une sauce à l'ail et à l'huile d'olive, imprégnant chaque bouchée de leur arôme et de leur saveur intenses. Une expérience culinaire irrésistible qui vous transportera sur les côtes espagnoles à chaque bouchée.",
        seleccionarMejillones: "Sélectionner les moules",
        rabasTitulo: "Calamars panés",
        rabasDesc: "Délicieux anneaux de calmars panés, croustillants à l'extérieur et tendres à l'intérieur, accompagnés d'une sauce moutarde épicée. La panure dorée met en valeur le goût doux et juteux des calmars, tandis que la sauce moutarde ajoute une touche audacieuse et délicieuse. Un plaisir irrésistible pour les amateurs de cuisine gastronomique.",
        seleccionarRabas: "Sélectionner les calmars",
        //Seccion postre
        postresTitulo: "DESSERTS",
        tiramisuTitulo: "Tiramisu",
        tiramisuDesc: "Un classique italien, indulgent et réconfortant. Des couches de gâteau imbibées de café, alternant avec un mélange crémeux de mascarpone, d'œufs et saupoudrées de cacao en poudre.",
        seleccionarTiramisu: "Sélectionner le tiramisu",
        cantidad: "Quantité :",
        higosTitulo: "Figues au sirop",
        higosDesc: "Figues dans un sirop doux et aromatique, mettant en valeur leur saveur naturelle et les rendant encore plus indulgentes. Parfaites en dessert ou en accompagnement.",
        seleccionarHigos: "Sélectionner des figues au sirop",
        brownieTitulo: "Brownie avec de la crème",
        brownieDesc: "Un cœur tentant de chocolat décadent et une texture dense et douce. Surmonté d'une généreuse boule de crème glacée à la crème sur un brownie chaud, créant une combinaison parfaite.",
        seleccionarBrownie: "Sélectionner brownie avec de la crème",
        //Seccion contacto
        formularioContacto: "Formulaire de contact",
        nombre: "Nom :",
        correoElectronico: "E-mail :",
        telefono: "Téléphone :",
        mensaje: "Message :",
        ubicacion: "Notre emplacement :",
        //Seccion mi pedido
        ordentitulo: "MA COMMANDE",
        mesanumero: "Numéro de table:",
        name: "Nom:",
        bebidaspedido: "Boissons",
        bebidasseleccionadas: "Ici irait ce qui a été sélectionné dans la boisson",
        entradaspedido: "Entrées",
        entradasseleccionadas: "Ici irait ce qui a été sélectionné dans l'entrée.",
        platospedidos: "Plats Principaux",
        platossleccionados: "Ici irait ce qui a été sélectionné dans le plat principal.",
        postrespedidos: "Desserts",
        postresseleccionados: "Ici irait ce qui a été sélectionné dans le dessert",
        submitorder: "Envoyer la Commande",

    }
};

function cambiarIdioma(lang) {
    const elements = document.querySelectorAll('[data-translate]');
    
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
}
